### PR TITLE
[Issue 54] Add 'selected' property to set selected items in  multi-select-menu.

### LINKED ISSUE #54: need ability to set value on multi-select-menu
need to update the menu based on its binding. blocks #2

### PR DESCRIPTION
**Pull request by dalogsdon**
Resolves #54

### CODE REVIEW

**Comment by dalogsdon** [comment]
Added `selected` property that sets values. This is similar to existing paper-selectable elements. 

2 questions to answer before bringing out of WIP status:

1. Should the `selected` property also get selected items (this would require more work to change how selection works)?
2. If it's only going to be a setter, changing the property bound to `selected` triggers a reselect. Would this be an issue?

**Comment by peller** [comment]
Seems like it would be cleanest to have `selected` be a getter and setter, also most consistent with `paper-*`

Not sure I understand the second question.  If you mean it brings up the select UI when the value is changed programmatically, that might be awkward, esp. if the value is restored with `JupyterPersistBehavior`

**Comment by peller** [comment]
change to `selected` array should probably deselect items previously selected, IOW prop should mirror the selected state of the whole list.  Is that how `selectedItems` works?

**Comment by dalogsdon** [comment]
`selectedItems` is computed based on selection made

**Comment by dalogsdon** [comment]
Updated to make `selected` property a getter and setter. It will always use the actual values of the items, not the index. I removed the `selectedItems` property since it was a duplicate.

**Comment by dalogsdon** [comment]
Updated due to comments from @peller

**Pull request merged**
