### PR TITLE
[Issue 63] Reset query columns when a group-by or agg changes.

### LINKED ISSUE #63: Update query.column as queries are formed
If a group-by and filter are both created, then filled in afterwards, both will reference the original column set.  Columns available to the filter should be dependent on the query generated by the group-by above it.

### PR DESCRIPTION
**Pull request by dalogsdon**
Resolves #63

### CODE REVIEW

**Comment by dalogsdon** [comment]
The only weird thing is that it takes an update cycle to propagate column changes, so an error can pop up if you modify a group followed by a derivative query, but then the subsequent update from that query changing will clear out the error.

**Comment by dalogsdon** [comment]
Looking with @peller we noticed an issue where error can happen outside of the event handlers i am using, I will see if there is a simple fix that can go in this pr.

**Comment by dalogsdon** [comment]
@peller I got a simple fix for removing a groupby that is the first query. See updates to `_queriesChanged()`.

**Comment by peller** [comment]
LGTM

**Pull request merged**
