### PR TITLE
Mixed protocol

### PR DESCRIPTION
**Pull request by peller**
@Etiennepi  I don't have a server set up with https.  Could you please test?

### CODE REVIEW

**Comment by peller** [comment]
Fixes #98

**Comment by Etiennepi** [comment]
Sure, is there an easy way to install only this modification, or should I setup a declarativewidgets dev environment?

**Comment by peller** [comment]
AFAIK, you need the dev environment

**Comment by Etiennepi** [comment]
Alright, I'll look into setting it up tomorrow, I'm in a bit of a rush atm.

**Comment by Etiennepi** [comment]
@peller I finally got around to setting everything up to test the change, sorry about the delay. So I tested it with the same dataset as well as in a few other notebooks and everything was fine, the graphs showed up with no problems.

**Pull request merged**
